"""The quarterly Field Medical Insight Report — a multi-agent fan-out/fan-in.
Chapter 4 §4.10.

This is the one place in InsightHub where multi-agent is the right answer, and
it is worth being precise about why:

  * The sub-tasks are genuinely independent. Analysing the durability theme tells
    you nothing you need in order to analyse the access theme.
  * Each sub-task generates a lot of intermediate context (searches, note text,
    evidence lookups) that the final writer does not need — only the conclusion.
    Sub-agents give you *context isolation*, which is the real benefit; the
    parallelism is a bonus.
  * The synthesis step needs all the conclusions at once, which is a natural
    fan-in.

When multi-agent is the WRONG answer: when sub-tasks share state, when they need
to negotiate, or when a single agent with a longer loop would do. Multi-agent
multiplies cost by the number of agents and makes failures much harder to
attribute. Reach for it when you can name the context-isolation benefit.
"""
from __future__ import annotations

from concurrent.futures import ThreadPoolExecutor
from dataclasses import dataclass, field

from . import llm
from .agent import AgentRun, run_agent
from .config import MODEL_DEEP, MODEL_WORK
from .themes import Theme
from .tools import Registry

THEME_BRIEF = """Analyse one theme for the quarterly Field Medical Insight Report.

Theme: {name}
Working summary: {summary}
Supporting insights ({n} total, showing up to 12):
{members}

Produce, using the tools:
1. How widespread is this? Distinct notes, distinct HCPs, regions, and the trend over
   the quarter. Use run_python to count; do not estimate.
2. Which published evidence addresses it, if any. Cite document IDs. If nothing does,
   say "evidence gap" explicitly — that is the most valuable finding you can return.
3. One recommended medical action, tied to a strategic priority (SP1-SP5), or "no action
   recommended" with a reason.

Be brief. Maximum 250 words. No attributed opinions — themes and counts only."""


SYNTHESIS_SYSTEM = """You write the executive section of a quarterly Field Medical
Insight Report for a pharmaceutical medical affairs leadership team.

Your readers are medical directors. They have fifteen minutes. They want to know what
changed, what it means, and what they should do — in that order.

Rules:
- Every claim traces to a theme analysis you were given. Add nothing.
- Lead with what changed this quarter, not with a description of the therapy area.
- Numbers must come from the analyses. Do not round them into vagueness ("many
  clinicians") — say "18 of 140 notes".
- Evidence gaps get their own section. They are the input to next year's medical plan.
- No named HCPs. No promotional language. No comparative claims that are not in a cited
  publication.
- If the analyses disagree with each other, say so rather than smoothing it over."""


@dataclass
class ThemeAnalysis:
    theme_id: str
    name: str
    text: str
    run: AgentRun | None = None
    cost_usd: float = 0.0


@dataclass
class Report:
    executive: str = ""
    analyses: list[ThemeAnalysis] = field(default_factory=list)
    cost_usd: float = 0.0

    def markdown(self) -> str:
        parts = ["# Quarterly Field Medical Insight Report", "",
                 "> Generated by InsightHub from synthetic data. Fictional product.",
                 "", "## Executive summary", "", self.executive, "",
                 "## Theme analyses", ""]
        for a in self.analyses:
            parts += [f"### {a.name}", "", a.text, ""]
        return "\n".join(parts)


def analyse_theme(theme: Theme, registry: Registry, *,
                  model: str = MODEL_WORK, max_steps: int = 8) -> ThemeAnalysis:
    members = "\n".join(f"- {t}" for t in theme.member_texts[:12])
    brief = THEME_BRIEF.format(name=theme.name or theme.representative,
                               summary=theme.summary, n=theme.size, members=members)
    run = run_agent(brief, registry, model=model, max_steps=max_steps,
                    max_cost_usd=0.40)
    return ThemeAnalysis(theme_id=theme.theme_id,
                         name=theme.name or theme.representative,
                         text=run.answer, run=run, cost_usd=run.cost_usd)


def build_report(themes: list[Theme], registry: Registry, *,
                 top_n: int = 8, worker_model: str = MODEL_WORK,
                 writer_model: str = MODEL_DEEP,
                 max_workers: int = 4) -> Report:
    """Fan out one sub-agent per theme, fan in to a single writer."""
    selected = themes[:top_n]
    with ThreadPoolExecutor(max_workers=max_workers) as pool:
        analyses = list(pool.map(
            lambda t: analyse_theme(t, registry, model=worker_model), selected))

    bundle = "\n\n".join(f"## {a.name}\n{a.text}" for a in analyses)
    res = llm.call(
        # claude-opus-5's adaptive thinking counts against max_tokens (see D-024,
        # D-026) — give headroom beyond the 400-600 word target so thinking over
        # up to 8 theme analyses can't starve the actual summary text.
        model=writer_model, max_tokens=6000, temperature=0.3,
        system=[{"type": "text", "text": SYNTHESIS_SYSTEM,
                 "cache_control": {"type": "ephemeral"}}],
        messages=[{"role": "user", "content":
                   f"Theme analyses for the quarter:\n\n{bundle}\n\n"
                   f"Write the executive summary (400-600 words) with sections: "
                   f"What changed this quarter; What it means; Evidence gaps; "
                   f"Recommended actions."}],
        meta={"step": "report_synthesis"},
    )
    return Report(executive=res.text, analyses=analyses,
                  cost_usd=sum(a.cost_usd for a in analyses) + res.cost_usd)
